### ISSUE TITLE
Geometry Wars TODO List

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGLGames#2]
- [X] Weapon types should not be selectable but should be automatically improved as the multiplier grows
- [X] Multiplier only grows when collecting crystals (by 1)
- [X] Multiplier "checkpoints" at 25 (add extra bullet), 50 (add extra bullet), 100 (add ricochet), 200 (add recharging shockwave)
